Traceback (most recent call last):
  File "/Users/wjohal/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/wjohal/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/wjohal/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/wjohal/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/wjohal/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/wjohal/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/wjohal/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/wjohal/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------

cv_image = image
ros, cols , channels = cv_image.shape
cv2.circle(cv_image, (cols/2,ros/2), 50, (0,0,255), -1)
image_pub.publish(bridge.cv2_to_imgmsg(cv_image,"brg8"))

rospy.init_node('image_processing')
bridge = CvBridge()
image_pub = rospy.Publisher("processed_image", Image)

while not rospy.is_shutdown():
    rospy.spin()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/7l/9dw_hz1s4h17g_7kmd29z_qr0000gn/T/ipykernel_42812/3828691977.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mcv_image[0m [0;34m=[0m [0mimage[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mros[0m[0;34m,[0m [0mcols[0m [0;34m,[0m [0mchannels[0m [0;34m=[0m [0mcv_image[0m[0;34m.[0m[0mshape[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0mcv2[0m[0;34m.[0m[0mcircle[0m[0;34m([0m[0mcv_image[0m[0;34m,[0m [0;34m([0m[0mcols[0m[0;34m/[0m[0;36m2[0m[0;34m,[0m[0mros[0m[0;34m/[0m[0;36m2[0m[0;34m)[0m[0;34m,[0m [0;36m50[0m[0;34m,[0m [0;34m([0m[0;36m0[0m[0;34m,[0m[0;36m0[0m[0;34m,[0m[0;36m255[0m[0;34m)[0m[0;34m,[0m [0;34m-[0m[0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mimage_pub[0m[0;34m.[0m[0mpublish[0m[0;34m([0m[0mbridge[0m[0;34m.[0m[0mcv2_to_imgmsg[0m[0;34m([0m[0mcv_image[0m[0;34m,[0m[0;34m"brg8"[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m

[0;31mNameError[0m: name 'image' is not defined
NameError: name 'image' is not defined

